#!/usr/bin/env bash
# Configure this Linux edge host as an NTP client of the PUDA site Chrony server.
# Do not run on the NATS/NTP host — that machine already runs infra/chrony.
#
# Usage:
#   sudo ./setup.sh <NTP_SERVER>
# NTP_SERVER is the Tailscale/LAN IP of infra/chrony (see README.md).

set -euo pipefail

NTP_SERVER="${1:-${NTP_SERVER:-}}"

if [[ "$(id -u)" -ne 0 ]]; then
  echo "Run as root: sudo $0 <NTP_SERVER>" >&2
  exit 1
fi

if [[ -z "$NTP_SERVER" ]]; then
  echo "NTP_SERVER is required (Tailscale/LAN IP of the site Chrony server)." >&2
  echo "Usage: sudo $0 <NTP_SERVER>" >&2
  exit 1
fi

if [[ "$NTP_SERVER" == "host.docker.internal" ]]; then
  echo "host.docker.internal is a Docker hostname. Use the NTP host Tailscale/LAN IP." >&2
  exit 1
fi

if command -v docker >/dev/null 2>&1; then
  if [[ "$(docker inspect -f '{{.State.Running}}' chrony 2>/dev/null || true)" == "true" ]]; then
    echo "Container 'chrony' is already running on this host (site NTP server)." >&2
    echo "Skip this client script; that container already disciplines this clock." >&2
    exit 1
  fi
fi

if ! command -v apt-get >/dev/null 2>&1; then
  echo "This script installs Chrony with apt-get (Debian/Ubuntu)." >&2
  echo "Install chrony yourself, point it at ${NTP_SERVER}, then: chronyc tracking" >&2
  exit 1
fi

export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq chrony

systemctl disable --now systemd-timesyncd 2>/dev/null || true
systemctl disable --now ntp ntpd 2>/dev/null || true

if [[ -d /etc/chrony ]]; then
  CONF=/etc/chrony/chrony.conf
else
  CONF=/etc/chrony.conf
fi

if [[ -f "$CONF" && ! -f "${CONF}.puda.bak" ]]; then
  cp "$CONF" "${CONF}.puda.bak"
fi

cat >"$CONF" <<EOF
# PUDA edge NTP client. Generated by test-edge/chrony/setup.sh
server ${NTP_SERVER} iburst
port 0
makestep 1.0 3
rtcsync
driftfile /var/lib/chrony/chrony.drift
EOF

# Ubuntu ships pool sources under sources.d; ignore them so we lock to site NTP.
if [[ -d /etc/chrony/sources.d ]]; then
  mkdir -p /etc/chrony/sources.d.disabled
  for src in /etc/chrony/sources.d/*; do
    [[ -e "$src" ]] || continue
    mv "$src" /etc/chrony/sources.d.disabled/
  done
fi

# Debian/Ubuntu: real unit is chrony.service; chronyd.service is an alias.
# RHEL/Fedora: real unit is chronyd.service. systemd 255+ refuses to enable aliases.
SVC=""
for candidate in chrony.service chronyd.service; do
  if [[ "$(systemctl show -p LoadState --value "$candidate" 2>/dev/null || true)" == "loaded" ]]; then
    SVC="$(systemctl show -p Id --value "$candidate")"
    break
  fi
done
if [[ -z "$SVC" ]]; then
  echo "Could not find a chrony systemd unit to enable." >&2
  exit 1
fi

systemctl enable --now "$SVC"
systemctl restart "$SVC"

sleep 2
echo "Chrony client pointed at ${NTP_SERVER}"
chronyc tracking
chronyc sources -v
