services:
  nats2:
    image: nats:2.14.5
    container_name: nats2
    restart: always
    ulimits:
      nofile:
        soft: 524288
        hard: 524288
    ports:
      - "${NATS_PORT:-4222}:4222"
      - "6222:6222"
      - "8222:8222"
      - "1883:1883"
    volumes:
      - nats2:/data
      - ./nats.conf:/etc/nats/nats.conf:ro
    environment:
      - SERVER_NAME=nats2
      - NATS_PORT=${NATS_PORT:-4222}
      - NATS1_ROUTE=nats-route://${NATS1_HOST}:6222
      - NATS2_ROUTE=nats-route://${HOST_IP}:6222
      - NATS3_ROUTE=nats-route://${NATS3_HOST}:6222
    command: "-c /etc/nats/nats.conf --client_advertise ${HOST_IP}:${NATS_PORT:-4222}"
    healthcheck:
      test:
        [
          "CMD",
          "nats",
          "server",
          "check",
          "jetstream",
          "--server",
          "localhost:4222",
        ]
      start_period: 10s

volumes:
  nats2:
